#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0
#
# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/ConquerOS/manifest.git -b twelve -g default,-mips,-darwin,-notdefault

# local manifest
git clone https://github.com/datnerdguy/local_manifest --depth 1 -b 12-4.19 .repo/local_manifests

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

tg "Cloned all Sources Successfully!
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
